name: Build Docker Image
on:
  pull_request:
  push:
#    branches:
#      - 'gh-readonly-queue/**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/${{ matrix.architecture }}

      - name: Set Git Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/${{ matrix.architecture }}
          tags: ghcr.io/badges/shields:pr-validation
          build-args: |
            version=${{ env.SHORT_SHA }}
